server:
  port: 9000

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/products_management
    username: usr
    password: password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info

token:
  minutes: 15
  issuer: "auth-service"

  private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDaObVfgB0UCd1AHULA859JkWp6tx/v3hCFw6rSYtf7jGC+FxCI0XYstUcInun0n6oo0lRBEtTF4FitUjZFgduAdwJvJ+O0yPbg/byzE1CRFTfPAlcUEKl5TE4lF8iYUMfTXL/aUjjpyBj5rqYuhERV5Pp7ti9tvKpdgGRtzsg8om3XTjtzn2nRFSvX8MYgpZNpYwNS161zCwU+n2K7FNgYW9CCwBm9gGrKtMLfmdHfm9LD7QlOsnaHgcZ+2Rk7y0PGEw02UFNtyJAfYZPofE4OOX14/A/08bjUhkOUnwZsJMwXjjnvHc/EZn3tCZjxLzYelDr8c8UoHkDIn5xoD1lvAgMBAAECggEAQq5Wiv9xIzHebtxiDOaEWiz6bdPuCNQAlXcUB+RXHdCnsP4IOd5TL1cXBP3V/D8bdgzK3PV9mZczUYao+bUz1r3GuyNjs1ajBV3THp78w9BJdNJAvGtY9a0IxdHOJCiu3pldMD9mj5zqcMTal6Un4l0s4sdpF62KGzcDuP/x9ICW/ao3S3fvfy1DLPoGUC35O3LRWz7WUp5xgiAVroYwoMn7F8eJ8f9l+j63iM/HHEZyxJosufhknqQi17V2zDXjQZhWitrVuL2sLwkUGM2OyfnA1G/okDWpZTDoA2wa+vi7cY6ZcVI2BDPMUakDJQmKJ/tCMITGHJZdeqKr3MyUrQKBgQDpeNVg9KbzhDVrbtgEvCe2Igat4wAi/UbFBVbvuS93ywTJpu6Do19QtZwu1xyVWGoGZ5NAvQ3UgfSByf1+jE6S6WCrkeTdE8PzPw8zi4kRV+n7FPPrZgxbp7172sx6NPOzHLw6oW0Wt/9FHaDWNwK7rhVYdPD0a/PYRp9pRSdqpQKBgQDvSEH8gtQKss0yrLHA4o3w5XZjsJ1Pa0fTUy587rwgq+fuehECgePk0tx1lqIx8uwJfeO1ga5d1T7PAkjnoNwyxTFY7X4zxe008S4dH1Fk8svOyKFN59Ko+k910qjfxNUdER1RoAjZb+NqUMuTI6f1wDC5IDMyYpWMLkP/hcT7gwKBgEKp/vt9QAJ+eKZhcwr/ErO9yXxzOcHD4iY1nRo8HWKuNILDyI0L5BZulNcHEyFNqpCDmJc+pClOphs9KsWsmG74dmLm+JtrnmLhWZzVNeEe4i+QTwmjDNpK7h7kXchzQDafeNug5j47cYcxq5AfCwe98Fheo8KW5HyXxcLQPS4FAoGBAICwvQSAnGgQl/nMFWGmty47Svv8re5bxWprj1IT18w+iGOi9OkDULzthzIazKrOepH0SfaBg3TlznzpPqqMwkDv+0VXnYtcxOG3YNS61jzTtDdHgjFzH8JPtVKp9Lc8ll2mqb0PtBK1cXrpb0N4ZsnuDoZSQha0HLgi3eFcYX/fAoGBAN05HqpeTDbXZZzwwscsIXoDfGgKpryy/pQ+5JlzGKzbZaMcldgoCxT4E4gljx/gHq/IKtSSaOT/eZvLshJreWUm5gMCIUmWUvjF5ar9uLCtZuI/XAGXQAU6sZkWyO1Lbb0y0aimoDDvWNlTzyDvsrsauNbSBIttUuxbuCK2roKn
    -----END PRIVATE KEY-----
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2jm1X4AdFAndQB1CwPOfSZFqercf794QhcOq0mLX+4xgvhcQiNF2LLVHCJ7p9J+qKNJUQRLUxeBYrVI2RYHbgHcCbyfjtMj24P28sxNQkRU3zwJXFBCpeUxOJRfImFDH01y/2lI46cgY+a6mLoREVeT6e7YvbbyqXYBkbc7IPKJt1047c59p0RUr1/DGIKWTaWMDUtetcwsFPp9iuxTYGFvQgsAZvYBqyrTC35nR35vSw+0JTrJ2h4HGftkZO8tDxhMNNlBTbciQH2GT6HxODjl9ePwP9PG41IZDlJ8GbCTMF4457x3PxGZ97QmY8S82HpQ6/HPFKB5AyJ+caA9ZbwIDAQAB
    -----END PUBLIC KEY-----