server:
  port: 8080

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          # Auth service JWK Set endpoint
          jwk-set-uri: http://127.0.0.1:9000/auth/jwks

  cloud:
    gateway:
      server:
        webflux:
          # All routes
          routes:
            - id: auth
              uri: http://127.0.0.1:9000
              predicates:
                - Path=/auth/**
              # no auth required (per SecurityConfig)

            - id: products
              uri: http://127.0.0.1:9001
              predicates:
                - Path=/api/v1/products/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@ipKeyResolver}"

            - id: payments
              uri: http://127.0.0.1:9002
              predicates:
                - Path=/api/v1/payments/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@ipKeyResolver}"

management:
  endpoints:
    web:
      exposure:
        include: health,info